# Generated by Django 4.2 on 2023-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='updated_a',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='updated_a',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='productinventory',
            old_name='updated_a',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_a',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='productinventory',
            table='Inventory',
        ),
    ]
